<body id="top">

    <section id="four" class="wrapper style4 special">
        <div class="inner">

            <header class="major2 narrow">
                <h2><?= Html::link('index/inicio', 'SEXYANUNCIOS.COM') ?></h2>
                <p>La mejor web de anuncios eróticos</p>
                
            </header>

            <?= Form::open() ?>
            <div class="container 75%">
                <div class="row uniform 50%">

                    <div class="6u 6u(xsmall)">
                            <!-- <input name="email" placeholder="Email" type="email" /> -->
                        <?= Form::email('usuarios.email', 'placeholder="Email"') ?>
                    </div>

                    <div class="6u 6u(xsmall)">
                            <!-- <input name="email" placeholder="Email" type="email" /> -->
                        <?= Form::pass('usuarios.password', 'placeholder="Contraseña"') ?>
                    </div>

                </div>
            </div>
            <ul class="actions1">
                <li>
                        <!-- <input type="submit" class="special" value="Submit" /> -->
                    <?= Form::submit('Iniciar Sesión', 'class="button special2"') ?>
                </li>

            </ul>
            <?= Form::close() ?>
            </form>
        </div>
    </section>

</body>



