<!-- Header -->
<header id="header" class="skel-layers-wraper">
   
    <h1><?= Html::link('index/inicio', 'SEXYANUNCIOS.COM') ?></h1>
    <nav id="nav">
        <ul>
            <li><?= Html::link('anuncios/listanuncio', 'Destacar') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Agencias') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Escorts') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Masajes') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Mis anuncios') ?></li>
            <li><?= Html::link('ciudades/ciudad', 'Ciudades') ?></li>
            <li><?= Html::link('login/login', 'Registrarse') ?></li>
            <li><?= Html::link('formularios/iniciosesion ', 'Iniciar sesión') ?></li>
            <li><?= Html::link('formularios/anunciogratis', 'Anunciate gratis', 'class="button special"') ?></li>      
        </ul>
    </nav>
   
</header>


