<!-- Header -->
<header id="header" class="skel-layers-wraper">
   
    <h1><?= Html::link('index', 'SEXYANUNCIOS.COM') ?></h1>
    <nav id="nav">
        <ul>
            <li><?= Html::link('anuncios/index', 'Destacar') ?></li>
            <li><?= Html::link('anuncios/index', 'Agencias') ?></li>
            <li><?= Html::link('anuncios/index', 'Escorts') ?></li>
            <li><?= Html::link('anuncios/index', 'Masajes') ?></li>
            <li><?= Html::link('anuncios/index', 'Mis anuncios') ?></li>
            <li><?= Html::link('anuncios/ciudades', 'Ciudades') ?></li>
            <li><?= Html::link('anuncios/login', 'Registrarse') ?></li>
            <li><?= Html::link('anuncios/iniciosesion', 'Iniciar sesión') ?></li>
            <li><?= Html::link('anuncios/formulario', 'Anunciate gratis', 'class="button special"') ?></li>      
        </ul>
    </nav>
   
</header>


