
<header id="header" class="skel-layers-wraper">

    <h1><?= Html::link('index/inicio', 'SEXXYANUNCIOS.COM') ?></h1>
    <nav id="nav">
        <ul>         
            <li><?= Html::link('anuncios/listanuncio', 'Agencias') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Escorts') ?></li>
            <li><?= Html::link('anuncios/listanuncio', 'Masajes') ?></li>
            
            <li>
                <?= Html::link('ciudades/ciudad', 'Ciudad') ?>
               
            </li>
            <li><?= Html::link('destacar/destacaranuncio', 'destacar', 'class="button special"') ?></li>
        </ul>
    </nav>

</header>

