<body id="top">

    <section id="four" class="wrapper style3 special">
        <div class="inner">
            <header class="major narrow">
                <h2><?= Html::link('index/inicio', 'SEXYANUNCIOS.COM') ?></h2>
                     <h2 class="h2m">Anuncio</h2>
            </header>



            <?= Form::open('anunciogratis', 'POST') ?>

            <div class="container 75%">
                <div class="row uniform1 50%">

                    <div class="6u">
                        <div class="select-wrapper">
                            <select name="category" id="Categorias">
                                <option value="">Categorias</option>
                                <option value="1">Hombres</option>
                                <option value="1">Mujeres</option>
                                <option value="1">Gays</option>
                                <option value="1">Lesbianas</option>
                                <option value="1">transexualex</option>
                                <option value="1">Juegos Sexuales</option>
                                <option value="1">Webcams Heroticas</option>
                                <option value="1">Habitaciones</option>
                                <option value="1">Otros</option>
                                <option value="1">Agencias</option>
                                <option value="1">Escorts</option>
                                <option value="1">Masajes</option>
                            </select>
                        </div>
                    </div>

                    <div class="6u">
                        <div class="select-wrapper">
                            <select name="category" id="Categorias">
                                <option value="">Ciudad</option>
                                <option value="1">A Coruña</option>
                                <option value="1">Álava</option>
                                <option value="1">Albacete</option>
                                <option value="1">Alicante</option>
                                <option value="1">Almería</option>
                                <option value="1">Asturias</option>
                                <option value="1">Ávila</option>
                                <option value="1">Badajoz</option>
                                <option value="1">Islas Baleares</option>
                                <option value="1">Barcelona</option>
                                <option value="1">Burgos</option>
                                <option value="1">Cáceres</option>
                                <option value="1">Cádiz</option>
                                <option value="1">Cantabria</option>
                                <option value="1">Lesbianas</option>
                                <option value="1">Castellón</option>
                                <option value="1">Ciudad real</option>
                                <option value="1">Córdoba</option>
                                <option value="1">Cuenca</option>
                                <option value="1">Girona</option>
                                <option value="1">Granada</option>
                                <option value="1">Guadalajara</option>
                                <option value="1">Guipúzcoa</option>
                                <option value="1">Huelva</option>
                                <option value="1">Huesca</option>
                                <option value="1">Jaén</option>
                                <option value="1">La Rioja</option>
                                <option value="1">Las Palmas</option>
                                <option value="1">León</option>
                                <option value="1">Lleida</option>
                                <option value="1">Lugo</option>
                                <option value="1">Madrid</option>
                                <option value="1">Málaga</option>
                                <option value="1">Murcia</option>
                                <option value="1">Navarra</option>
                                <option value="1">Orence</option>
                                <option value="1">Palencia</option>
                                <option value="1">Pontevedra</option>
                                <option value="1">Salamanca</option>
                                <option value="1">Lleida</option>
                                <option value="1">Segovia</option>
                                <option value="1">Sevilla</option>
                                <option value="1">Soria</option>
                                <option value="1">Tarragona</option>
                                <option value="1">Santa Cruz de Tenerife</option>
                                <option value="1">Teruel</option>
                                <option value="1">Toledo</option>
                                <option value="1">Valencia</option>
                                <option value="1">Valladolid</option>
                                <option value="1">Vizcaya</option>
                                <option value="1">Zamora</option>
                                <option value="1">Zaragoza</option>       
                            </select>
                        </div>
                    </div>



                    <div class="6u 12u (xsmall)">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.titulo', 'placeholder="Titulo para el anuncio"') ?>
                    </div>

                    <div class="6u 12u (xsmall)">
                            <!-- <input name="name" placeholder="Name" type="text" /> -->
                        <?= Form::text('usuario.name', 'placeholder="Horario disponible"') ?>
                    </div>


                    <div class="6u 12u (xsmall)">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.moviluno', 'placeholder="Movil Uno" ') ?>
                    </div>




                    <div class="6u 12 (xsmall)u">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.movildos', 'placeholder="Movil  Dos"') ?>
                    </div>  

                    <div class="12u (xsmall)">
                            <!-- <textarea name="message" placeholder="Message" rows="4"></textarea> -->
                        <?= Form::textarea('usuario.message', 'placeholder="Message" rows="4"') ?>
                    </div>


                    <section class="special box5">

                        <h2 class="h2">servicios</h2>
                        <div class="row uniform1 50%">

                            <div class="special box7">
                                <input type="checkbox" id="69" name="69">
                                <label for="69">69</label>
                            </div>
                            <div class="special box7">
                                <input type="checkbox" id="oral" name=";oral;">
                                <label for="oral">Oral</label>
                            </div>
                            <div class="special box7">
                                <input type="checkbox" id="domina" name="domina">
                                <label for="domina">Domina</label>
                            </div>
                            <div class="special box8">
                                <input type="checkbox" id="estriptis" name="estriptis" >
                                <label for="estriptis">Estriptis</label>
                            </div>
                            <div class="special box9">
                                <input type="checkbox" id="sexoanal" name="sexoanal" >
                                <label for="sexoanal">Sexo anal</label>
                            </div>
                            <div class="special box10">
                                <input type="checkbox" id="fetichismo" name="fetichismo" >
                                <label for="fetichismo">Fetichismo</label>
                            </div>
                            <div class="special box11">
                                <input type="checkbox" id="lluviadorada" name="lluviadorada" >
                                <label for="lluviadorada">Lluvia dorada</label>
                            </div>
                            <div class="special box12">
                                <input type="checkbox" id="masajeerotico" name="masajeerotico" >
                                <label for="masajeerotico">Masaje erotico</label>
                            </div>
                            <div class="special box13">
                                <input type="checkbox" id="masajetantrico" name="masajetantrico" >
                                <label for="masajetantrico">Masaje tantrico</label>
                            </div>
                            <div class="special box14">
                                <input type="checkbox" id="oralconcondon" name="oralconcondon" >
                                <label for="oralconcondon">Oral con condon</label>
                            </div>
                            <div class="special box15">
                                <input type="checkbox" id="masajeprostatico" name="masajeprostatico" >
                                <label for="masajeprostatico">Masaje prostatico</label>
                            </div>
                            <div class="special box16">
                                <input type="checkbox" id="juguetessexuales" name="juguetessexuales" >
                                <label for="juguetessexuales">Juguetes sexuales</label>
                            </div>
                            <div class="special box17">
                                <input type="checkbox" id="eyaculacioncorporal" name="eyaculacioncorporal" >
                                <label for="eyaculacioncorporal">Eyaculación corporal</label>
                            </div>
                            <div class="special box18">
                                <input type="checkbox" id="salidaarestaurantes" name="salidaarestaurantes" >
                                <label for="salidaarestaurantes">Salida a restaurantes</label>
                            </div>
                            <div class="special box19">
                                <input type="checkbox" id="salidacomoacompañante" name="salidacomoacompañante" >
                                <label for="salidacomoacompañante">Salida de acompañante</label>
                            </div>
                        </div>
                    </section> 

                    <section class=" special box20"> 
                        <h2 class="h2n">Información</h2>
                    </section>

                    <div class="6u 12u (xsmall)">   
                     <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.pais', 'placeholder="Nacionalidad"') ?>
                    </div>

                    <div class="6u 12u (xsmall)">
                            <!-- <input name="name" placeholder="Name" type="text" /> -->
                        <?= Form::text('usuario.edad', 'placeholder="Edad"') ?>
                    </div>


                    <div class="6u 12u (xsmall)">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.peso', 'placeholder="Peso" ') ?>
                    </div>

                    <div class="6u 12 (xsmall)u">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.estatura', 'placeholder="Estatura"') ?>
                    </div>  

                    <div class="6u 12u (xsmall)">   
                    <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.ojos', 'placeholder="Color de ojos"') ?>
                    </div>

                    <div class="6u 12u (xsmall)">
                            <!-- <input name="name" placeholder="Name" type="text" /> -->
                        <?= Form::text('usuario.pelo', 'placeholder="Color de pelo"') ?>
                    </div>


                    <div class="6u 12u (xsmall)">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.pecho', 'placeholder="Tamaño de los pechos" ') ?>
                    </div>

                    <div class="6u 12 (xsmall)u">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.pubis', 'placeholder="Vello púbico (depilada)"') ?>
                    </div>  


                </div>
            </div> 





            <ul class="actions">
                <li>
                        <!-- <input type="submit" class="special" value="Submit" /> -->
                    <?= Form::submit('Subir Anuncio', 'class="button special"') ?>
                </li>

            </ul>
            <?= Form::close() ?>
        </div>

    </section>

</body>

