<body id="top">

    <section id="four" class="wrapper style3 special">
        <div class="inner">
            <header class="major narrow">
                <h2>sexyanuncios</h2>
                <p>La mejor web de anuncios eróticos <a href="http://SexyAnuncios.com"></a></p>
            </header>



            <?= Form::open('anunciogratis', 'POST') ?>

            <div class="container 75%">
                <div class="row uniform 50%">

                    <div class="6u">
                        <div class="select-wrapper">
                            <select name="category" id="Categorias">
                                <option value="">Categorias</option>
                                <option value="1">Hombres</option>
                                <option value="1">Mujeres</option>
                                <option value="1">Gays</option>
                                <option value="1">Lesbianas</option>
                                <option value="1">transexualex</option>
                                <option value="1">Juegos Sexuales</option>
                                <option value="1">Webcams Heroticas</option>
                                <option value="1">Habitaciones</option>
                                <option value="1">Otros</option>
                                <option value="1">Agencias</option>
                                <option value="1">Escorts</option>
                                <option value="1">Masajes</option>
                            </select>
                        </div>
                    </div>

                    <div class="6u">
                        <div class="select-wrapper">
                            <select name="category" id="Categorias">
                                <option value="">Ciudades</option>
                                <option value="1">A Coruña</option>
                                <option value="1">Álava</option>
                                <option value="1">Albacete</option>
                                <option value="1">Alicante</option>
                                <option value="1">Almería</option>
                                <option value="1">Asturias</option>
                                <option value="1">Ávila</option>
                                <option value="1">Badajoz</option>
                                <option value="1">Islas Baleares</option>
                                <option value="1">Barcelona</option>
                                <option value="1">Burgos</option>
                                <option value="1">Cáceres</option>
                                <option value="1">Cádiz</option>
                                <option value="1">Cantabria</option>
                                <option value="1">Lesbianas</option>
                                <option value="1">Castellón</option>
                                <option value="1">Ciudad real</option>
                                <option value="1">Córdoba</option>
                                <option value="1">Cuenca</option>
                                <option value="1">Girona</option>
                                <option value="1">Granada</option>
                                <option value="1">Guadalajara</option>
                                <option value="1">Guipúzcoa</option>
                                <option value="1">Huelva</option>
                                <option value="1">Huesca</option>
                                <option value="1">Jaén</option>
                                <option value="1">La Rioja</option>
                                <option value="1">Las Palmas</option>
                                <option value="1">León</option>
                                <option value="1">Lleida</option>
                                <option value="1">Lugo</option>
                                <option value="1">Madrid</option>
                                <option value="1">Málaga</option>
                                <option value="1">Murcia</option>
                                <option value="1">Navarra</option>
                                <option value="1">Orence</option>
                                <option value="1">Palencia</option>
                                <option value="1">Pontevedra</option>
                                <option value="1">Salamanca</option>
                                <option value="1">Lleida</option>
                                <option value="1">Segovia</option>
                                <option value="1">Sevilla</option>
                                <option value="1">Soria</option>
                                <option value="1">Tarragona</option>
                                <option value="1">Santa Cruz de Tenerife</option>
                                <option value="1">Teruel</option>
                                <option value="1">Toledo</option>
                                <option value="1">Valencia</option>
                                <option value="1">Valladolid</option>
                                <option value="1">Vizcaya</option>
                                <option value="1">Zamora</option>
                                <option value="1">Zaragoza</option>       
                            </select>
                        </div>
                    </div>

                    <div class="6u 12u$xsmall">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.titulo', 'placeholder="Titulo para el anuncio"') ?>
                    </div>

                    <div class="6u 12u">
                            <!-- <input name="name" placeholder="Name" type="text" /> -->
                        <?= Form::text('usuario.name', 'placeholder="Horario disponible"') ?>
                    </div>


                    <div class="6u 12u$xsmall">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.moviluno', 'placeholder="Movil Uno" ') ?>
                    </div>

                    <div class="6u 12u$xsmall">   
                       <!-- <input name="soy" placeholder="Soy" type="text" />-->
                        <?= Form::text('usuario.movildos', 'placeholder="Movil  Dos"') ?>
                    </div>  

                    <div class="12u">
                            <!-- <textarea name="message" placeholder="Message" rows="4"></textarea> -->
                        <?= Form::textarea('usuario.message', 'placeholder="Message" rows="4"') ?>
                    </div>
                    <section class="special box5">
                        <h2>servicios</h2>
                        <div class="row uniform 50%">
                            
                            <div class="3u 4u(xsmall)">
                              
                                <input type="checkbox" id="besoconlengua" name="priority" >
                                <label for="besoconlengua">&nbsp;&nbsp;Beso con lengua&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="cunnilingus" name="priority">
                                <label for="cunnilingus">&nbsp;Cunnilingus</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="lesbico" name="priority">
                                <label for="lesbico">&nbsp;&nbsp;Juego lesbico&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="oral" name="priority">
                                <label for="oral">&nbsp;&nbsp;&nbsp;&nbsp;Oral&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="oralconcondon" name="priority">
                                <label for="oralconcondon">&nbsp;&nbsp;Oral con condon&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="restaurante" name="priority">
                                <label for="restaurante">Restaurante</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="sexoanal" name="priority">
                                <label for="sexoanal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sexo&nbsp; anal
                                                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="sesentaynueve" name="priority">
                                <label for="sesentaynueve">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;69&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="masajeprostatico" name="priority">
                                <label for="masajeprostatico">&nbsp;Masaje prostatico</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="fetichismo" name="priority">
                                <label for="fetichismo">&nbsp;Fetichismo&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="lluviadorada" name="priority">
                                <label for="lluviadorada">&nbsp;&nbsp;Lluvia &nbsp;dorada&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="viajes" name="priority">
                                <label for="viajes">&nbsp;&nbsp;Viajes&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="juguetessexuales" name="priority">
                                <label for="juguetessexuales">Juguetes sexuales</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="sumision" name="priority">
                                <label for="sumision">&nbsp;&nbsp;Sumisión&nbsp;&nbsp;&nbsp;</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="masajeherotico" name="priority">
                                <label for="masajeherotico">Masaje herotico</label>
                            </div>
                            <div class="3u 4u(xsmall)">
                                <input type="checkbox" id="estriptis" name="priority">
                                <label for="estriptis">Estriptis</label>
                            </div>    
                        </div>
                    </section>    

                </div>
            </div> 
            <ul class="actions">
                <li>
                        <!-- <input type="submit" class="special" value="Submit" /> -->
                    <?= Form::submit('Subir Anuncio', 'class="button special"') ?>
                </li>

            </ul>
            <?= Form::close() ?>
        </div>

    </section>

</body>

