<body id="top">
    <section id="main" class="wrapper style3">
        <div class="inner"> 
            <header class="major narrow">
                <h2>sexyanuncios</h2>
                <ul class="actions">
                </ul>
            </header> 



            <div class="container">
                <div class="row">


                    
                    <div class="6u">
                        <section class="special box1">
                           <a href="personalbanner/anuncios" class="image fit1"><?= Html::img('imagesex1.jpg', '') ?></a>
                            
                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos </p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">

                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>

                                </ul>
                            </section>
                        </section>

                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="personalbanner/anuncios" class="image fit1"><?= Html::img('sexi2.jpg', '') ?></a>                            
                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                  
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('sexi6.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">
                            <a href="#" class="image fit1"><?= Html::img('sexi1.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="" class="image fit1"><?= Html::img('fondo.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">
                            <a href="#" class="image fit1"><?= Html::img('inicio12.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('sexi6.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">
                            <a href="#" class="image fit1"><?= Html::img('sexi2.jpg', '') ?></a>

                            <section class="especial box2">
                                <p class="p1">somos una pareja liberal y nos gustaria conoserte llamanos no te arrepentiras estamos dispuestos
                                    a todo marca nuestro</p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                  
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                   
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                    
                    <div class="6u">
                        <section class="special box1">

                            <a href="#" class="image fit1"><?= Html::img('', '') ?></a>

                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>




                </div>
            </div>
        </div>
    </section>
</body>
