<body id="top">
    <section id="main" class="wrapper style3">
        <div class="inner"> 
            <header class="major narrow">
                <h2>sexyanuncios</h2>
                <ul class="actions">
                </ul>
            </header> 


            <div class="container">
                <div class="row">
                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('imagesex1.jpg', 'imagesex1'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">

                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>

                                </ul>
                            </section>
                        </section>

                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('sexi2.jpg', 'sexi2'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('sexi6.jpg', 'sexi6'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('sexi1.jpg'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('fondo.jpg', 'fondo'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('inicio12.jpg', 'inicio12'), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>

                    <div class="6u">
                        <section class="special box1">
                            <?= Html::link('bannerpersonal/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box2">
                                <p class="p1"></p>  
                            </section>
                            <section class="especial box2">
                                <ul class="actions">
                                    <li><?= Html::link('anuncios/personalbanner', 'Contactar', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Faboritos', 'class="button special1"') ?></li>
                                    <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                </ul>
                            </section>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

