<body id="top">
    <section id="main" class="wrapper style3">
        <div class="inner"> 
            <header class="major narrow">
                <h2><?= Html::link('index/inicio', 'SEXXYANUNCIOS.COM') ?></h2>
                <ul class="actions">
                </ul>
            </header> 


            <div class="container">
                <div class="row">
                    
                    <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('imagesex1.jpg', 'imagesex1'), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">

                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>

                                    </ul>
                                </section>
                            </section>
                        </section>

                    </div>

                    <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('sexi2.jpg', 'sexi2'), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1">hola soy manuela y he vuelto asevilla, te espero</p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>

                    <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('sexi6.jpg', 'sexi6'), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>

                    <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('d1.jpg', 'imagen'), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                
                    <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('pic01.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('inicio12.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('d2.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('d3.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('d4.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('d5.jpg', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                     <div class="4u">
                        <section class="special box1">
                            <?= Html::link('usuarios/cliente', Html::img('', ''), 'class="image fit1"') ?>
                            <section class="especial box6">
                                <p class="p1"></p>  

                                <section class="especial box2">
                                    <ul class="actions2">
                                        <li><?= Html::link('usuarios/cliente', 'Contactar', 'class="button special1"') ?></li>
                                        <li><?= Html::link('anuncios/formulario', 'Denunciar', 'class="button special1"') ?></li>
                                    </ul>
                                </section>
                            </section>
                        </section>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </section>
</body>
                    