
<?php View::partial('partialssexianuncios/headeruno') ?>
<section id="main" class="wrapper style3">
    <div class="inner"> 
        <header class="major narrow">
            <h2><?= Html::link('index/inicio', 'SEXXYANUNCIOS.COM') ?></h2>
            <p>La mejor web de anuncios eróticos</p>
        </header> 
        <div class="container">
            <div class="row">
                <div class="4u">
                    <a href="usuarios/cliente" class="girl_box">
                        <div class="image-wrapper">
                            <div class="wishlist_icon" data-girl_stamp="92r9s3M3FQ09Ptkc">
                                <div class="wishlist_icon_img" alt="Add to wishlist"></div>
                            </div>
                            
                            <div class="image-carousel" data-number-slide="8" data-current-slide="0">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/d1.jpg" alt="" class="img-responsive" style="margin-left: 0%;">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/d2.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/d3.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/d4.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/d5.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/sexi6.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/sexi2.jpg" alt="" class="img-responsive">
                                <img src="/AnunciosREPO/proyecto-master/default/public/img/pic01.jpg" alt="Britney, escort, Eaux-Vives, BeMyGirl" class="img-responsive">
                            </div>
                            <div class="image-hover">
                                <div class="vcenter text-center">
                                    <div class="vchild">
                                        <div class="image-title white"></div>
                                        <div class="image-place small white">
                                            <span class="pink"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>     
                        </div>
                    </a>                   
                </div>
            </div>
        </div>
    </div>
</section>
