<body id="top">
    <?php View::partial('partialssexianuncios/headertres') ?>
    <section id="four" class="wrapper style4 special">
        <div class="inner"> 
            <header class="major2 narrow">
                <h2>sexxyanuncios</h2>
                <p>La mejor web de anuncios eróticos <a href="http://SexyAnuncios.com"></a></p><br>

                <p>Para destacar tu anuncio y ubicarlo  en las primeras posiciones debes disponer de  bonos sexx, estos los puedes<br>
                    conseguir pulsando el boton adquirir bonos, se debe tener en cuenta que para obtener estos bonos hay que <br>
                    estar registrado, si no lo estas pulsa el boton registrar, si ya estas registrado solo tienes que pulsar adquirir 
                    bonos.<br>
                    Los anuncios destacados tienen prioridad sobre los otros anuncios.
                </p>

                <ul class="actions">
                    <li>
                        <h4><?= Html::link('usuarios/iniciarsesion', 'adquirir bonos', 'class="button special"') ?></h4>
                    </li>
                    </ul>
                    <ul class="actions">
                    <li>
                        <h4><?= Html::link('usuarios/registrar', 'registrar', 'class="button special"') ?></h4>
                    </li>
                </ul>
            </header>
        </div>
    </section>
</body>

