<section id="banner">
    <div class="inner">
        <h2>SexyAnuncios</h2>
        <p>La mejor web de anuncios eróticos <a href="http://SexiAnuncios.com"></a></p>
        <!--
        Asi se usa el Helper linkAction (crea un link) para 
        pasarle parametros (usuarios[0]->id) al metodo del controlador 
        indicado (cambiarDatoUsuario) como terminacion de la url,
        teniendo que el texto a mostrar de dicho link es "Cambio"
        -->
        <?= Html::linkAction('cambiarDatoUsuario/' . $usuarios[0]->id, 'Cambio', '') ?>
        <ul class="actions">
            
        </ul>
    </div>
</section>

<section id="one" class="wrapper style1">	

    <div class="container">

        <div class="row">
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Hombres') ?></h4></div>                    
                    <a href="anuncios/index" class="image fit"> <?= Html::img('hombre5.jpg', '') ?></a> 
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Mujeres') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('mujer1.png', '') ?></a>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Gays') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('gay1.png', '') ?></a>
                </section>
            </div>	
        </div>

        <div class="row">
            <div class="4u">
                <section class="special box">	
                    <div class=""><h4><?= Html::link('anuncios/index', 'Lesbianas') ?></h4></div>
                    <a href="anuncios/index" class="image fit"> <?= Html::img('gay.png', '') ?></a>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Transexuales') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('trans2.png', '') ?></a>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Juegos sexuales') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('esposas.png', '') ?></a>
                </section>
            </div>			
        </div>

        <div class="row">
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Webcams heroticas') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('cam1.jpg', '') ?></a>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Habitaciones') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('habitacion.png', '') ?></a>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <div class=""><h4><?= Html::link('anuncios/index', 'Otros') ?></h4></div>					
                    <a href="anuncios/index" class="image fit"> <?= Html::img('mas1.png', '') ?></a>
                </section>
            </div>			
        </div>

    </div>
</section>
