<section id="banner">
    <div class="inner">
        <h2>SexyAnuncios</h2>
        <p>La mejor web de anuncios eróticos <a href="http://SexiAnuncios.com"></a></p>
        <ul class="actions">

        </ul>
    </div>
</section>

<section id="one" class="wrapper style1">	

    <div class="container">

        <div class="row">
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Hombres') ?></h4>                     
                    <?= Html::link('anuncios/listanuncio', Html::img('hombre5.jpg', 'hombres'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Mujeres') ?></h4>
                    <?= Html::link('anuncios/listanuncio', Html::img('mujer1.png', 'mujer1'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Gays') ?></h4>					
                    <?= Html::link('anuncios/listanuncio', Html::img('gay1.png', 'gay1'), 'class="image fit"') ?>
                </section>
            </div>	
        </div>

        <div class="row">
            <div class="4u">
                <section class="special box">	
                    <h4><?= Html::link('anuncios/listanuncio', 'Lesbianas') ?></h4>
                    <?= Html::link('anuncios/listanuncio', Html::img('gay.png', 'gay'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Transexuales') ?></h4>
                    <?= Html::link('anuncios/listanuncio', Html::img('trans2.png', 'trans2'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Juegos sexuales') ?></h4>					
                    <?= Html::link('anuncios/listanuncio', Html::img('esposas.png', 'esposas'), 'class="image fit"') ?>
                </section>
            </div>			
        </div>

        <div class="row">
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Webcams heroticas') ?></h4>					
                    <?= Html::link('anuncios/listanuncio', Html::img('cam1.jpg', 'cam1'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Habitaciones') ?></h4>					
                    <?= Html::link('anuncios/listanuncio', Html::img('habitacion.png', 'habitacion'), 'class="image fit"') ?>
                </section>
            </div>
            <div class="4u">
                <section class="special box">
                    <h4><?= Html::link('anuncios/listanuncio', 'Otros') ?></h4>					
                    <?= Html::link('anuncios/listanuncio', Html::img('mas1.png', 'mas1'), 'class="image fit"') ?>
                </section>
            </div>			
        </div>

    </div>
</section>

